version: "3"
services:
  web:
    image: carshow
    environment:
      - ALLOW_OVERRIDE=true
    ports:
      - "81:80"
      - "444:443"
    links:
      - db
    volumes: # ambos volumenes (a los dos lados de ":") son punteros a los mismos ficheros, por lo que si editamos cualquiera, se modifican ambos (si hay diferentes ficheros se juntan)
      - ./app:/var/www/html/
      - ./logs:/var/log/apache2
      - ./virtualhost/certificados:/etc/apache2/ssl
      - ./virtualhost/carshow.conf:/etc/apache2/sites-enabled/carshow.conf
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backups:/var/backups
      - ./crontabs:/var/spool/cron/crontabs

  db:
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    #command: --default_authentication_plugin=caching_sha2_password
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root1234"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin1234"
      MYSQL_DATABASE: "COCHES"
    ports:
      - "8889:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    links:
      - db
    ports:
      - 8890:80
    environment:
      MYSQL_USER: "admin" #usuario admin para phpmyadmin (root)
      MYSQL_PASSWORD: "admin1234" #contraseña para admin en phpmyadmin (root)
      MYSQL_DATABASE: "COCHES"
